services:
  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    env_file:
      - .env.docker
    ports:
      - '54321:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    env_file:
      - .env.docker
    ports:
      - '5050:80'
    depends_on:
      - postgres

volumes:
  postgres-data:
